/*
** EPITECH PROJECT, 2024
** MyTeams
** File description:
** protocol
*/

#pragma once

#include <sys/select.h>

typedef enum ptc_state {
    HELP = 214,
    LOGGED_OUT = 221,
    LOGGED_IN = 230,
    COMMAND_SUCCESS = 200,
    UNKNOWN_USER = 400,
    SYNTAX_ERROR = 500,
    ERROR_PARAMETERS = 501,
    TOO_MORE_PARAMETERS = 502,
    TOO_FEW_PARAMETERS = 503,
    NOT_LOGGED_IN = 530,
    NO_CONTEXT = 531,
    MESSAGE_SEND = 600,
    MESSAGE_RECIEVE = 601,

    CLIENT_EVENT_LOGGED_IN = 700,
    CLIENT_EVENT_LOGGED_OUT = 710,
    CLIENT_EVENT_PRIVATE_MESSAGE_RECEIVED = 720,
    CLIENT_EVENT_THREAD_REPLY_RECEIVED = 730,
    CLIENT_EVENT_TEAM_CREATED = 740,
    CLIENT_EVENT_CHANNEL_CREATED = 750,
    CLIENT_EVENT_THREAD_CREATED = 760,
    CLIENT_PRINT_USERS = 770,
    CLIENT_PRINT_TEAMS = 780,
    CLIENT_TEAM_PRINT_CHANNELS = 790,
    CLIENT_CHANNEL_PRINT_THREADS = 800,
    CLIENT_THREAD_PRINT_REPLIES = 810,
    CLIENT_PRIVATE_MESSAGE_PRINT_MESSAGES = 820,
    CLIENT_ERROR_UNKNOWN_TEAM = 830,
    CLIENT_ERROR_UNKNOWN_CHANNEL = 840,
    CLIENT_ERROR_UNKNOWN_THREAD = 850,
    CLIENT_ERROR_UNKNOWN_USER = 860,
    CLIENT_ERROR_UNAUTHORIZED = 870,
    CLIENT_ERROR_ALREADY_EXIST = 880,
    CLIENT_PRINT_USER = 890,
    CLIENT_PRINT_TEAM = 900,
    CLIENT_PRINT_CHANNEL = 910,
    CLIENT_PRINT_THREAD = 920,
    CLIENT_PRINT_TEAM_CREATED = 930,
    CLIENT_PRINT_CHANNEL_CREATED = 940,
    CLIENT_PRINT_THREAD_CREATED = 950,
    CLIENT_PRINT_REPLY_CREATED = 960,
    CLIENT_PRINT_SUBSCRIBED = 970,
    CLIENT_PRINT_UNSUBSCRIBED = 980
} ptc_state_t;

/**
 * @brief send a msg to a given file descriptor
 *
 * @param state the protocol state
 * @param msg body of the message
 * @param fd file descriptor to writte in
 * @param writefds ...
 */
void ptc_send(ptc_state_t state, char *msg, int fd, fd_set *writefds);
