/*
** EPITECH PROJECT, 2024
** MyTeams
** File description:
** protocol
*/

#pragma once

#include <sys/select.h>

typedef enum ptc_state {
    HELP = 214,
    LOGGED_OUT = 221,
    LOGGED_IN = 230,
    COMMAND_SUCCESS = 200,
    UNKNOWN_USER = 400,
    SYNTAX_ERROR = 500,
    ERROR_PARAMETERS = 501,
    TOO_MORE_PARAMETERS = 502,
    TOO_FEW_PARAMETERS = 503,
    NOT_LOGGED_IN = 530,
    MESSAGE_SEND = 600,
    MESSAGE_RECIEVE = 601,

    CLIENT_EVENT_LOGGED_IN = 200,
    CLIENT_EVENT_LOGGED_OUT = 210,
    CLIENT_EVENT_PRIVATE_MESSAGE_RECEIVED = 220,
    CLIENT_EVENT_THREAD_REPLY_RECEIVED = 230,
    CLIENT_EVENT_TEAM_CREATED = 240,
    CLIENT_EVENT_CHANNEL_CREATED = 250,
    CLIENT_EVENT_THREAD_CREATED = 260,
    CLIENT_PRINT_USERS = 270,
    CLIENT_PRINT_TEAMS = 280,
    CLIENT_TEAM_PRINT_CHANNELS = 290,
    CLIENT_CHANNEL_PRINT_THREADS = 300,
    CLIENT_THREAD_PRINT_REPLIES = 310,
    CLIENT_PRIVATE_MESSAGE_PRINT_MESSAGES = 320,
    CLIENT_ERROR_UNKNOWN_TEAM = 330,
    CLIENT_ERROR_UNKNOWN_CHANNEL = 340,
    CLIENT_ERROR_UNKNOWN_THREAD = 350,
    CLIENT_ERROR_UNKNOWN_USER = 360,
    CLIENT_ERROR_UNAUTHORIZED = 370,
    CLIENT_ERROR_ALREADY_EXIST = 380,
    CLIENT_PRINT_USER = 390,
    CLIENT_PRINT_TEAM = 400,
    CLIENT_PRINT_CHANNEL = 410,
    CLIENT_PRINT_THREAD = 420,
    CLIENT_PRINT_TEAM_CREATED = 430,
    CLIENT_PRINT_CHANNEL_CREATED = 440,
    CLIENT_PRINT_THREAD_CREATED = 450,
    CLIENT_PRINT_REPLY_CREATED = 460,
    CLIENT_PRINT_SUBSCRIBED = 470,
    CLIENT_PRINT_UNSUBSCRIBED = 480
} ptc_state_t;

/**
 * @brief send a msg to a given file descriptor
 *
 * @param state the protocol state
 * @param msg body of the message
 * @param fd file descriptor to writte in
 * @param writefds ...
 */
void ptc_send(ptc_state_t state, char *msg, int fd, fd_set *writefds);
