name : Mirroring

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"
env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-NWP-400-NAN-4-1-myteams-theophile.jerome-rocher.git"
  EXECUTABLES: "myteams_server,myteams_cli"

jobs:
  check_program_compilation:
    runs-on : ubuntu-latest
    container : epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name : "checkout"
        uses : actions/checkout@v3
      - name : "make"
        run : "make"
      - name : "make clean"
        run : "make clean"
      - name: "Valid Executables"
        run: |
          IFS=','
          string="${{ env.EXECUTABLES }}"
          for exec in $string; do
            if ! [ -x "$exec" ] || ! [ -f "$exec" ]; then
              exit 42
            fi
          done
  
  run_tests:
    needs: check_program_compilation
    timeout-minutes : 2
    runs-on: ubuntu-latest
    container : epitechcontent/epitest-docker
    steps:
      - name : "checkout"
        uses : actions/checkout@v3
      - name : "tests"
        run : |
          PATH=$(pwd)
          LD_LIBRARY_PATH=$PATH/libs/myteams:$LD_LIBRARY_PATH make tests_run
  push_to_mirror:
    needs : run_tests
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

